name: Android APK

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    
jobs:
    apk:
      if: "!contains(github.event.head_commit.message, 'skip ci')"
      name: Generate APK
      
      runs-on: ubuntu-latest

      steps:
        - uses: actions/checkout@v2
        - name: set up JDK 1.8
          uses: actions/setup-java@v1
          with:
            java-version: 1.8
        - name: Build debug APK
          run: bash ./gradlew assembleDebug --stacktrace
        - name: Upload APK
          uses: actions/upload-artifact@v2.2.1
          with:
            name: app
            path: app/build/outputs/apk/debug/app-debug.apk
